TRAIN:
  ENABLE: True
  DATASET: ssv1
  BATCH_SIZE: 64
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 20
  AUTO_RESUME: True
TEST:
  ENABLE: True
  DATASET: ssv1
  BATCH_SIZE: 16
  # 6-views
  NUM_ENSEMBLE_VIEWS: 2
  NUM_SPATIAL_CROPS: 3
  # single clip & single crop
#  NUM_ENSEMBLE_VIEWS: 1
#  NUM_SPATIAL_CROPS: 1
DATA:
  NUM_FRAMES: 16
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  INV_UNIFORM_SAMPLE: True
  RANDOM_FLIP: False
  REVERSE_INPUT_CHANNEL: True
  PATH_TO_DATA_DIR: /home/lsrock1/data/sth-sth-v1/20bn-something-something-v1
  PATH_PREFIX: /home/lsrock1/data/sth-sth-v1/20bn-something-something-v1
VOV3D:
  DEPTH: 31
  TRANS_FUNC: t_osa_2plus1_transform
  NUM_CONV: 4
  INNER_CH: 48
  TEMPORAL_DILATIONS: [[1], [1], [1], [1]]
RESNET:
  ZERO_INIT_FINAL_BN: True
  NUM_BLOCK_TEMP_KERNEL: [[1],[1],[1],[1]]
  SPATIAL_STRIDES: [[2], [2], [2], [2]]
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  BASE_LR_SCALE_NUM_SHARDS: True
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 1.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 174
  ARCH: vov3d
  MODEL_NAME: VoV3D
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 8
RNG_SEED: 0
LOG_MODEL_INFO: True
TENSORBOARD:
  ENABLE: True
OUTPUT_DIR: output/SSv1/vov3d/VoV3D_M_F16_fromScratch
